services:
  tai-mysql-db:
    container_name: tai-mysql-db
    image: mysql:8.0.32
    ports:
      - '${TAI_MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${TAI_MYSQL_PASSWORD}
      MYSQL_DATABASE: library-db
    volumes:
      - ./.volumes/mysql/mysql-volume:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -u root -p${TAI_MYSQL_PASSWORD}"
    networks:
      - tai-network

  tai-phpmyadmin:
    container_name: tai-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${TAI_PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: tai-mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${TAI_MYSQL_PASSWORD}
    depends_on:
      - tai-mysql-db
    networks:
      - tai-network

  tai-server:
    container_name: tai-server
    build:
      context: ./tai-server
      dockerfile: Dockerfile
    ports:
      - ${TAI_SERVER_PORT}:9672
    environment:
      TAI_PORT: 9672
      TAI_DB_HOST: tai-mysql-db
      TAI_DB_NAME: library-db
      TAI_DB_USERNAME: root
      TAI_DB_PASSWORD: ${TAI_MYSQL_PASSWORD}
      TAI_CLIENT_URL: http://localhost:9673
      TAI_SERVER_XMS: 1024m
      TAI_SERVER_XMX: 1024m
    depends_on:
      - tai-mysql-db
    networks:
      - tai-network

  tai-client:
    container_name: tai-client
    build:
      context: ./tai-client
      dockerfile: Dockerfile
      args:
        TAI_CONTEXT: development
    ports:
      - ${TAI_CLIENT_PORT}:9673
    networks:
      - tai-network

networks:
  tai-network:
    driver: bridge