server:
  port: 9076

spring:
  datasource:
    url: jdbc:mysql://${TAI_DB_HOST}:3306/${TAI_DB_NAME}
    username: ${TAI_DB_USERNAME}
    password: ${TAI_DB_PASSWORD}
  liquibase:
    contexts: lq_prod

management:
  endpoints:
    web:
      exposure:
        include: health
