server:
  port: ${TAI_PORT:9076}
  servlet:
    session:
      cookie:
        secure: true

spring:
  datasource:
    url: jdbc:mysql://${TAI_DB_HOST}:${TAI_DB_PORT:3306}/${TAI_DB_NAME}
    username: ${TAI_DB_USERNAME}
    password: ${TAI_DB_PASSWORD}
  liquibase:
    contexts: lq_prod
  mail:
    port: ${TAI_MAIL_PORT:587}
    username: ${TAI_MAIL_USERNAME}
    password: ${TAI_MAIL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health

application:
  cors:
    urls:
      - ${TAI_CLIENT_URL:https://tai.miloszgilga.pl}
  mail:
    from: ${TAI_MAIL_FROM_ADDRESS}
    client-url: ${TAI_CLIENT_URL:https://tai.miloszgilga.pl}
