server:
  port: 9076
  servlet:
    session:
      cookie:
        secure: true

spring:
  datasource:
    url: jdbc:mysql://${TAI_DB_HOST}:3306/${TAI_DB_NAME}
    username: ${TAI_DB_USERNAME}
    password: ${TAI_DB_PASSWORD}
  liquibase:
    contexts: lq_prod

management:
  endpoints:
    web:
      exposure:
        include: health

application:
  cors:
    urls:
      - https://tai.miloszgilga.pl
