server:
  port: 9672

spring:
  devtools:
    livereload:
      port: 35731
      enabled: false
    restart:
      log-condition-evaluation-delta: false
  datasource:
    url: jdbc:mysql://localhost:9670/library-db
    username: root
    password: admin
  liquibase:
    contexts: lq_dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
