FROM caddy:latest

ENV BUILD_DIR=/docker
ENV ENTRY_DIR=/app/tai-client

COPY $BUILD_DIR/dist/ $ENTRY_DIR
COPY $BUILD_DIR/Caddyfile /etc/caddy/Caddyfile

LABEL maintainer="Miłosz Gilga <personal@miloszgilga.pl>"

EXPOSE 9673
