-- liquibase formatted sql
-- changeset milosz08:8

CREATE TABLE IF NOT EXISTS books
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

  title VARCHAR(255) NOT NULL,
  isbn VARCHAR(18) NOT NULL,
  year INTEGER NOT NULL,
  publisher VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  copies INTEGER UNSIGNED NOT NULL DEFAULT 0,

  PRIMARY KEY (id)
)
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS authors
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  book_id BIGINT UNSIGNED NOT NULL,

  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
)
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_books
(
  book_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,

  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB;
