-- liquibase formatted sql
-- changeset milosz08:1

CREATE TABLE IF NOT EXISTS roles
(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

	name ENUM('CUSTOMER', 'EMPLOYER', 'ADMIN') NOT NULL,

	PRIMARY KEY (id)
)
ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS users
(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(150) NOT NULL,
	password VARCHAR(60) NOT NULL,
	active BOOL NOT NULL DEFAULT FALSE,
	role_id BIGINT UNSIGNED NOT NULL,

	FOREIGN KEY (role_id) REFERENCES roles(id),
	PRIMARY KEY (id)
)
ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS addresses
(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	street VARCHAR(100) NOT NULL,
	building_number VARCHAR(10) NOT NULL,
	apartment_number VARCHAR(10) DEFAULT NULL,
	city VARCHAR(100) NOT NULL,
	user_id BIGINT UNSIGNED NOT NULL,

	FOREIGN KEY (user_id) REFERENCES users(id),
	PRIMARY KEY (id)
)
ENGINE=InnoDB;
