name: Deploy client

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/client.yml"
      - "tai-client/**"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: cd tai-client && yarn install --frozen-lockfile

      - name: Build
        run: cd tai-client && yarn run build

  deploy:
    runs-on: self-hosted
    needs: build
    env:
      ROOT_PATH: "tai-library-client"

    steps:
      - name: Copy compiled static files
        run: |
          rm -rf /var/www/$ROOT_PATH/*
          rm -rf /var/www/$ROOT_PATH/{*,.[!.]*,..?*} 2> /dev/null
          cp -r tai-client/dist/* /var/www/$ROOT_PATH/
