name: Deploy client

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/client.yml"
      - "client/**"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: cd client && yarn install --frozen-lockfile

      - name: Build
        run: cd client && yarn run build

      - name: Deploy
        run: cp -r client/dist/* /var/www/tai-library-client/
