name: Create docker image and upload to DockerHub

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/docker-image.yml"
      - "docker/entrypoint"
      - "tai-client/**"
      - "tai-server/**"
      - "Dockerfile.pipeline"
      - "pom.xml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
          check-latest: false

      - name: Change wrapper permissions
        run: chmod +x ./mvnw

      - name: Clean build dir
        run: ./mvnw clean

      - name: Package to JAR
        run: ./mvnw package

      - name: Upload generated JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-jar
          path: .bin/library-app-tai.jar
          retention-days: 1

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download generated JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: output-jar
          path: ${{ github.workspace }}/docker

      - name: Set up builder
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.pipeline
          push: true
          tags: milosz08/library-app-tai:latest

      - name: Logout from Docker Hub
        run: docker logout
