name: Build and deploy server

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/server.yml"
      - "tai-server/**"

env:
  SUBPROJECT_ROOT: "tai-server"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          check-latest: false

      - name: Change wrapper permissions
        run: cd ${{ env.SUBPROJECT_ROOT }} && chmod +x ./mvnw

      - name: Clean build dir
        run: cd ${{ env.SUBPROJECT_ROOT }} && ./mvnw clean

      - name: Package to JAR
        run: cd ${{ env.SUBPROJECT_ROOT }} && ./mvnw package

      - name: Upload generated JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-jar
          path: ${{ env.SUBPROJECT_ROOT }}/target/tai-server.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      PM2_API_NAME: "TAIProjectAPI"
      SERVER_OUTPUT: "/var/www/tai-library-server"

    steps:
      - name: Download generated JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: output-jar

      - name: Stop existing process
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: ~/exec/process stop ${{ env.PM2_API_NAME }}

      - name: Move files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "tai-server.jar"
          target: ${{ env.SERVER_OUTPUT }}
          rm: true

      - name: Re-create config file
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: ~/exec/make-conf ${{ env.SERVER_OUTPUT }} ${{ secrets.CONFIG_FILE_CONTENT }}

      - name: Start process
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: ~/exec/process start ${{ env.PM2_API_NAME }}
