name: Deploy server

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/server.yml"
      - "tai-server/**"

env:
  SUBPROJECT_ROOT: "tai-server"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          check-latest: false

      - name: Change wrapper permissions
        run: cd $SUBPROJECT_ROOT && chmod +x ./mvnw

      - name: Clean build dir
        run: cd $SUBPROJECT_ROOT && ./mvnw clean

      - name: Package to JAR
        run: cd $SUBPROJECT_ROOT && ./mvnw package

  deploy:
    runs-on: self-hosted
    needs: build
    env:
      PM2_API_NAME: "TAIProjectAPI"
      ROOT_PATH: "tai-library-server"

    steps:
      - name: Stop existing process
        run: |
          pm2 stop /root/ecosystem.config.js --only $PM2_API_NAME --silent
          pm2 save

      - name: Copy compiled executable files
        run: |
          rm -rf /var/www/$ROOT_PATH/*
          rm -rf /var/www/$ROOT_PATH/{*,.[!.]*,..?*} 2> /dev/null
          cp $SUBPROJECT_ROOT/target/tai-server.jar /var/www/$ROOT_PATH

      - name: Re-create config file
        run: |
          touch /var/www/$ROOT_PATH/.env
          echo "${{ secrets.CONFIG_FILE_CONTENT }}" > /var/www/$ROOT_PATH/.env

      - name: Start process
        run: |
          pm2 start /root/ecosystem.config.js --only $PM2_API_NAME --silent
          pm2 save
